//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Support.sitecore_modules.Web.Web_Forms_for_Marketers.UI.UserControl
{


  public partial class Captcha
  {
  }
}
